FIXUP: FROMGIT: mmc: mediatek: Fix system suspend/resume support for CQHCI
0-day reports:

drivers/mmc/host/mtk-sd.c:2773:12: error:
	'msdc_resume' defined but not used [-Werror=unused-function]
drivers/mmc/host/mtk-sd.c:2759:12: error:
	'msdc_suspend' defined but not used [-Werror=unused-function]

The functions are declared within CONFIG_PM but used from CONFIG_PM_SLEEP.
The above problem is seen if CONFIG_PM is enabled and CONFIG_PM_SLEEP
is disabled. Marking the functions as __maybe unused fixes the problem.

BUG=b:153618576
TEST=boot asurada, read/write test pass

Change-Id: Ibd352ef4b0f26953101dab0b1ddd09b052624593
Disallow-Recycled-Builds: test-failures
Reported-by: kernel test robot <lkp@intel.com>
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/2570565
Reviewed-by: Nicolas Boichat <drinkcat@chromium.org>